query-service-client/build.gradle.kts, query-service/build.gradle.kts
=> Update grpc utils with changes for binary headers.

query-service-api/build.gradle.kts, query-service-api/src/test/java/org/hypertrace/core/query/service/api/QueryRequestTest.java, query-service-impl/build.gradle.kts, query-service-impl/src/main/java/org/hypertrace/core/query/service/RequestHandler.java, query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/Params.java, query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandler.java, query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
You can either take the query to reconstruct the proto or get the full sql
so that you can debug it much more quickly.
Also did a bunch of code cleanup.
=> Changing the slow queries format to be easily usable for debugging.

README.md
This PR,
- adds query architecture and explains query service in that context
- adds build steps and image source i.e. docker hub link in  README
=> adds query architecture, working, build steps and image source in README

README.md
This PR,
- Adds how to run unit tests
- Adds how to test locally built image with docker-compose
- rearranges sections in README
=> adds testing section and rearranges sections as per suggestions

query-service-impl/build.gradle.kts, query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/StringToValueConverter.java
This also brings new capability where we can get column data type
from the ResultSet.
=> Upgrading Pinot client to the latet version.

.circleci/config.yml, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
Update framework version for vulnerability fixes, limit snyk to run on runtime code.
- [n/a] I have added tests that prove my fix is effective or that my feature works
=> chore: update vulnerable dependencies

query-service-impl/build.gradle.kts
=> Pinot 0.6 upgrade

query-service/src/main/resources/configs/common/application.conf
Map attributes added for spaces - see hypertrace/hypertrace#142
Manually spun up with this change
=> refactor: add space cols to qs config

query-service/src/main/resources/configs/common/application.conf
Related to https://github.com/hypertrace/hypertrace/issues/176
=> Query: Add api_exit_calls field

query-service-client/build.gradle.kts, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
=> chore: Upgrade deps to fix vulnerabilities

query-service/src/main/resources/configs/common/application.conf
=> feat: Add api_callee_name_count field in api-traces-view-handler

query-service/src/main/resources/configs/common/application.conf
Adding destination field in query-service config as we are working on adding destination column in Backend Trace (call) view.
NA
=> chore: adding backend_destination field in query service config

build.gradle.kts, query-service-api/build.gradle.kts, query-service-client/build.gradle.kts, query-service-impl/build.gradle.kts, query-service/build.gradle.kts, settings.gradle.kts
Update vulnerable dependencies
=> chore: update vulnerabilities

query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java, query-service/src/main/resources/configs/common/application.conf
Add LogEventView
hypertrace/hypertrace#224
=> feat: Log view handler

query-service/src/main/resources/configs/common/application.conf
=> fix: Undo config changes

query-service/src/main/resources/configs/common/application.conf
Add summary col
hypertrace/hypertrace#224
=> feat: Add summary col

query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotClientFactory.java
Added debug statement for Pinot Query statement resolution
=> Added debug statement for Pinot Query statement resolution

.snyk, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
Quick fix for some vulnerabilities raised by snyk
=> chore: update dependencies for vulnerabilities

query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/ExecutionContextTest.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandlerTest.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/projection/ProjectionTransformationTest.java
Updated unit tests to resolve mockito issues
=> Fix : Updated unit tests

query-service-impl/build.gradle.kts, query-service/build.gradle.kts
=> fix: update vulnerable log4j

.snyk, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
Update vulnerable dependencies
=> chore: update vulnerable deps

query-service-impl/build.gradle.kts, query-service/build.gradle.kts
=> chore: update log4j version to 2.17.0

query-service-api/build.gradle.kts, query-service-client/build.gradle.kts, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
PR,
- upgrades a few libs to take care of snyk failures.
=> chore:fixed snyk failures

query-service-factory/build.gradle.kts, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
Update service framework version
=> chore: update framework version

.github/workflows/pr-build.yml
added container scanning to query-service repo
=> added container scanning to query-service repo

query-service-impl/build.gradle.kts, query-service-impl/src/main/java/org/hypertrace/core/query/service/postgres/PostgresClientFactory.java
Bug in parsing config into postgres client
=> fix: postgres password

query-service-impl/src/main/java/org/hypertrace/core/query/service/postgres/PostgresBasedRequestHandler.java
Addressed comment - https://github.com/hypertrace/query-service/commit/a8fbb972a0895277c803094a6a81a346898d4842#r80417446
=> fix: adds value type as part of the response null string response

query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
Reverts hypertrace/query-service#170
=> Revert "fix: add support for boolean array fields for pinot"

query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/Params.java, query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverter.java, query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/converters/DefaultColumnRequestConverter.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java, query-service-impl/src/test/resources/trino_request_handler.conf
=> ENG-35526: add support for Trino boolean type

helm/values.yaml, owasp-suppressions.xml, query-service-impl/build.gradle.kts, query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/converters/DefaultColumnRequestConverter.java, query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java, query-service/build.gradle.kts, query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java
=> add support for map type in Trino handler

owasp-suppressions.xml, query-service-client/build.gradle.kts, query-service-factory/build.gradle.kts, query-service-impl/build.gradle.kts, query-service/build.gradle.kts
updated service framework version to expose latency histogram metrics for grpc services
=> updated service framework version
