- query-service-impl/build.gradle.kts
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/Params.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotClientFactory.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/ViewDefinition.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/StringToValueConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/ToValueConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/resources/request_handler.conf
- query-service/src/main/resources/configs/common/application.conf
There are few strings IDs fields are maps to bytes column in pinot, as part of this PR,
- adds support for handling filtering query on such fields by type conversion (e.g parent_span_id != 'null')
- fails fast on invalid string input for such fields if it fails to convert to valid hex string
- re-factored init steps for pinot query conversion tests
> adds supports for filtering on bytes ID columns

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/StringToValueConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/StringToValueConverterTest.java
This PR handles the filter scenario for bytes type,
```
childFilter {
childFilter {
lhs {
columnIdentifier {
columnName: "EVENT.id"
}
}
operator: EQ
rhs {
literal {
value {
string: "{}"
}
}
}
}
}
}
```
It adds '{}' as a valid list of null values for bytes field
> Handling the empty bracket scenario for bytes filter

- .snyk
- query-service-impl/build.gradle.kts
Fixes for vulnerabilities still not available even in the latest versions of io netty and zookeeper dependencies.
Failure in build:
```
Issues with no direct upgrade or patch:
✗ HTTP Request Smuggling [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-IONETTY-473694] in io.netty:netty@3.10.3.Final
introduced by org.apache.pinot:pinot-java-client@0.5.0 > io.netty:netty@3.10.3.Final
No upgrade or patch available
✗ Deserialization of Untrusted Data [High Severity][https://snyk.io/vuln/SNYK-JAVA-LOG4J-572732] in log4j:log4j@1.2.17
introduced by org.apache.zookeeper:zookeeper@3.6.1 > log4j:log4j@1.2.17 and 1 other path(s)
No upgrade or patch available
```
> chore: fix snyk failures

- .snyk
- query-service/build.gradle.kts
Ignore then in .snyk file since there are no patches for them
> fix: snyk ionetty vulberability warnings

- .github/workflows/merge-publish.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish.yml
To remove ambiguity, we have decided to keep our GitHub customs actions in a repo named `hypertrace/github-actions` (https://github.com/hypertrace/github-actions) instead of `hypertrace/actions` (https://github.com/hypertrace/actions) and this PR will solve any failures that might happen after deletion of `hypertrace/actions` repo. 
Already merged here: https://github.com/hypertrace/attribute-service/pull/66
> ci: handles github actions repo name change

- query-service/src/main/resources/configs/common/application.conf
Adding backend_operation field in query-service config as we are working on adding Operation column in Backend Trace (call) view.
NA
> feat: adding backend_operation field in query service config

- query-service-impl/src/main/java/org/hypertrace/core/query/service/projection/ProjectionTransformation.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/projection/ProjectionTransformationTest.java
When projecting attributes, sometimes we write those projections into pinot for query performance. In those cases, the query should not be transformed - this change reads the materialized flag off the attribute definition to decide whether to proceed with transformation.
Ran E2E, updated UTs
> fix: ignore materialized projections

- query-service/src/main/resources/configs/common/application.conf
Adds api_trace_error_count attribute as per changes here: hypertrace/hypertrace-ingester#172
NA
> chore: adds api_trace_error_span_count attribute

- query-service-impl/build.gradle.kts
- query-service/build.gradle.kts
Use newer attribute client with better performing client (builds errors lazily, less exception filling)
> chore: use newer attribute client with lazy errors

- .github/workflows/pr-test.yml
Codecov bash uploader is being deprecated and is currently in the brownout phase. We need to upgrade to the v2 gh action in all repos.
More info: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
> ci: update codecov

- query-service/src/main/resources/configs/common/application.conf
Ref issue : https://github.com/hypertrace/hypertrace-ui/issues/1157
> Addition of span count attribute

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/resources/service_request_handler.conf
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/ServicesQueries.java
On the service (backend) screen page, there is a rate column - `error/s`. After we moved the avgrate functionality to query-service, the sorting on this column is broken.
The reason it was broken, that avgrate function takes two arguments (column name, size). The second size argument is missing in `order by` expression. Priori, it was working fine as `avgrate` was translated to `sum` at the gateway service layer. And `sum` function needs only single column name argument.
As these rate columns are per second rate, for now, defaulting to `PT1S` as size for avgrate function to fix the regression.
> fix : sorting rate metrics

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/MigrationTest.java
Ref issue : https://github.com/hypertrace/query-service/issues/104
> Added support for handling simple attribute expression

- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryRequestUtil.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandler.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/projection/ProjectionTransformation.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/prometheus/FilterToPromqlConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/prometheus/PrometheusBasedRequestHandler.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/prometheus/PrometheusUtils.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/prometheus/QueryRequestEligibilityValidator.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/prometheus/QueryRequestToPromqlConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/MigrationTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandlerTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/projection/ProjectionTransformationTest.java
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/QueryServiceTestUtils.java
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/ExplorerQueries.java
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java
Ref issue : https://github.com/hypertrace/query-service/issues/105
> Added support for handling complex attribute expression.

- query-service-api/src/main/proto/request.proto
- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryRequestUtil.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/ExecutionContextTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/MigrationTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandlerTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/projection/ProjectionTransformationTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/prometheus/QueryRequestToPromqlConverterTest.java
Ref issue : https://github.com/hypertrace/query-service/issues/122 , https://github.com/hypertrace/query-service/issues/109
> Fix : Add support for contains key and like operator

- query-service-impl/build.gradle.kts
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/projection/ProjectionTransformationTest.java
- query-service/build.gradle.kts
Followup from #129 - new test for a projection of an attribute expression with subpath, and upgrading log4j for a minor vulnerability that doesn't affect this service.
Ran all tests locally.
> test: add projection with subpath test

- query-service-api/build.gradle.kts
- query-service-impl/build.gradle.kts
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandler.java
- query-service/build.gradle.kts
> chore: include execution stats when logging slow query warn message

- .snyk
- query-service-api/build.gradle.kts
Updated vulnerable dependencies that had a new version available, put a short ignore on those that did not.
> chore: update dependency constraints and exclusions

- helm/templates/query-service-config.yaml
- helm/values.yaml
- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryServiceConfig.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryServiceImpl.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryServiceModule.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/LimitValidation.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/QueryValidation.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/QueryValidationModule.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/QueryValidator.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/TenantValidation.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryServiceImplTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/validation/LimitValidationTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/validation/QueryValidatorTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/validation/TenantValidationTest.java
- query-service-impl/src/test/resources/application.conf
- query-service/src/main/resources/configs/common/application.conf
This PR adds configurable limit validation. It supports setting a minimum limit (preventing things like negative values, or unlimited queries), maximum limit, and a mode. The three modes are WARN (which logs limit breaches, but does not reject them), ERROR (which... errors) and DISABLED (probably self explanatory). Min and Max values are inclusive. Defaults are set to a limit of 1-10K, in warn mode. In practice this means warning logs will fire for any unlimited query, or a query with a limit > 10K.
Added new unit tests for all new code, as well as updating existing test paths.
> feat: add configurable limit validation

- query-service-impl/src/main/java/org/hypertrace/core/query/service/validation/LimitValidation.java
Followup to https://github.com/hypertrace/query-service/pull/135 to actually print offending query in log message.
> fix: actually print offending request for limit warning

- query-service-impl/src/main/java/org/hypertrace/core/query/service/QueryServiceImpl.java
Currently, there are no metrics to track the number of failed requests in the data query layer. Adding an error counter to track requests failing in query service. The metric is exposed on /metrics endpoint.  
For gateway-service - [https://github.com/hypertrace/gateway-service/pull/128](url)
> added error count of failed requests from query service to pinot

- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java
Deps on : https://github.com/hypertrace/pinot/pull/106/files
> fix: the integration test with latest pinot image for group.id change

- .snyk
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotBasedRequestHandler.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterConfig.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterTest.java
- query-service-impl/src/test/resources/application.conf
- query-service/src/integrationTest/java/org/hypertrace/core/query/service/htqueries/HTPinotQueriesTest.java
- Adds the ability to configure the aggregation used for DISTINCTCOUNT, defaulting to the existing implementation which is the exact computation. Behavior of various versions of this function are described in https://docs.pinot.apache.org/users/user-guide-query/how-to-handle-unique-counting
- Updates the avg rate function to use the `/` operator rather than the existing `DIV()`. This is better optimized by Pinot.
- Refactored config of aggregation configuration for easier extendability
Ran and updated unit tests
> feat: support configuring distinct count agg function

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterTest.java
Flip division from inside sum aggregation to outside, allowing pinot to optimize with star tree.
Unit tests, verified optimization with pinot explain plain
> fix: flip around division

- query-service-api/src/main/proto/request.proto
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
This PR adds `CONTAINS_KEY_LIKE` operator for doing a regex based search on map fields (on map key column). 
Added unit test.
> feat: add CONTAINS_KEY_LIKE operator

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/QueryRequestBuilderUtils.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
This PR adds support for queries involving boolean array fields for Pinot.
Sample failing query  - 
```
{
"filter": {
"operator": "AND",
"childFilter": [
{
"lhs": {
"attribute_expression": {
"attributeId": "API.isExternal",
"alias": "isExternal"
}
},
"rhs": {
"literal": {
"value": {
"valueType": "BOOLEAN_ARRAY",
"boolean_array": [false]
}
}
},
"operator":"IN"
}
]
},
"limit": 1,
"selection": [
{
"attribute_expression": {
"attributeId": "API.isExternal",
"alias": "isExternal"
}
}
]
}
```
Added new unit tests for all new code, and ran all the existing unit tests.
> fix: add support for boolean array fields for pinot

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterConfig.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterTest.java
Existing config supports configuring the distinct count aggregation function for a given scope for all attributes. But we might need accurate distinct count on some attributes if the default is set to the approximate function. Defined a way to configure such attributes.
> Added support for accurate distinct count on attributes through config

- query-service-api/build.gradle.kts
- query-service-factory/build.gradle.kts
- query-service-impl/build.gradle.kts
- query-service/build.gradle.kts
Fix vulnerabilities -
```
Testing /Users/kshitizsaxena/SourceCode/hypertrace/query-service...
Organization:      saxenakshitiz
Package manager:   gradle
Target file:       build.gradle.kts
Project name:      query-service
Open source:       no
Project path:      /Users/kshitizsaxena/SourceCode/hypertrace/query-service
Local Snyk policy: found
Licenses:          enabled
✔ Tested /Users/kshitizsaxena/SourceCode/hypertrace/query-service for known issues, no vulnerable paths found.
Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
-------------------------------------------------------
Testing /Users/kshitizsaxena/SourceCode/hypertrace/query-service...
Tested 102 dependencies for known issues, found 5 issues, 14 …
```
> ENG-26854: Fix vulnerabilities in query-service

- query-service-impl/build.gradle.kts
Runtime failure was due to missing "org.apache.log4j.Logger". This dependency was coming from zkclient. Added a constraint to user version "0.11" of zkclient to remove log4j dependency.
> fix: fix runtime failure

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/PinotColumnSpec.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/ViewDefinition.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverterTest.java
- query-service-impl/src/test/resources/request_handler.conf
This PR add support for utilising text indexes for LIKE operator for pinot based request handler if the index for those column is enabled. So, the string column with index will translated to 
- text_match(column, /\<value\>/)
- Added the request conversation test.
> feat: add support for utilising text indexes if exits for like operator in pinot based handlers

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterConfig.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/converters/PinotFunctionConverterTest.java
As part of this PR, we extend of support for using different aggregation function for distinct count query for multi value column.
Currently, we do support the same for single value field via below config at request handler level:
```
distinctCountAggFunction = DISTINCTCOUNTHLL
distinctCountAggOverrides = {
"attribute_id_1" = DISTINCTCOUNT
}
```
It tells that, for all the single value attribute except `attribute_id_1` of the request handler, it will use `DISTINCTCOUNTHLL` function.
We are extending above as below:
```
distinctCountAggFunction = DISTINCTCOUNTHLL
distinctCountMvAggFunction = DISTINCTCOUNTHLLMV
distinctCountAggOverrides = {
"attribute_id_1" = DISTINCTCOUNT
"attribute_mv_1" = DISTINCTCOUNT
}
```
The above config tells that,
- for all multi-value attribute except …
> feat: extend the support for distinct count for multi-value

- query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/pinot/MigrationTest.java
This pull request introduces an additional value filter for map columns, aiming to enhance performance by utilizing the underlying inverted index on the `__keys` and `__values` columns of the Pinot implementation.
This optimisation is specifically applied to queries like `mapValue(tags__keys, 'flags', tags__values) = '0'`.
This approach is the same as the one followed in the deprecated `CONTAINS_KEYVALUE`.
Ref: https://github.com/hypertrace/query-service/blob/b89ebf416e876959586d47f8e67f126be239c7d5/query-service-impl/src/main/java/org/hypertrace/core/query/service/pinot/QueryRequestToPinotSQLConverter.java#L181
Modified the existing test case.
> fix: adds values filter for map column

- query-service-impl/build.gradle.kts
Ref : https://github.com/hypertrace/query-service/actions/runs/5556670054/jobs/10149475819
- `okio-jvm` is transitive deps via `okhttp`
- `okhttp` non-alpha release version is still using `okio's` 3.2.0 version. The issue is fixed in `3.4.0` so we are fixing via constriants.
> fix: updates libs for vuln fixes

- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/converters/DefaultColumnRequestConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java
> ENG-35614: add support for bytes type in Trino handler

- owasp-suppressions.xml
- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverter.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/TrinoBasedRequestHandler.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/TrinoFilterHandler.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java
> add support for delegating query to Trino handler based on isTrino attribute

- helm/templates/deployment.yaml
- query-service/build.gradle.kts
As part of this PR,
- adding TRINO_PASSWORD envs as part of deployment
> chore: adding trino related env variables

- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/TrinoBasedRequestHandler.java
- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/TrinoFilterHandler.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java
> fix IS_TRINO_ATTRIBUTE and compare with ignore case

- owasp-suppressions.xml
- query-service-client/build.gradle.kts
- query-service-factory/build.gradle.kts
- query-service-impl/build.gradle.kts
- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/TrinoBasedRequestHandler.java
- query-service/build.gradle.kts
> truncate Trino query error message to 2K

- query-service-impl/src/main/java/org/hypertrace/core/query/service/trino/converters/TrinoFunctionConverter.java
- query-service-impl/src/test/java/org/hypertrace/core/query/service/trino/QueryRequestToTrinoSQLConverterTest.java
> support dateTimeConvert function in Trino

- owasp-suppressions.xml
- query-service-api/build.gradle.kts
- query-service-client/build.gradle.kts
- query-service-factory/build.gradle.kts
- query-service-impl/build.gradle.kts
- query-service/build.gradle.kts
Update dependencies and suppressions
> chore: update deps, suppressions

- query-service-impl/build.gradle.kts
fixes:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.logging.slf4j.Log4jLoggerFactory.<init>(org.apache.logging.slf4j.Log4jMarkerFactory)'
at org.apache.logging.slf4j.SLF4JServiceProvider.initialize(SLF4JServiceProvider.java:57)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
at org.hypertrace.core.serviceframework.PlatformServiceLauncher.<clinit>(PlatformServiceLauncher.java:14)
```
> chore: exclude transitive dependency log4j-slf4j-impl
